### ISSUE TITLE
Feature: Auto-close completed orders

### ISSUE THREAD

**Issue by martinskalicky** [recursivetree/seat-alliance-industry#4]
Hello,

it would be great to be able to set up (config?) **automatic-closing or completed orders**.

People very often forget to close their orders and then we have to go to seat - impersonate and close them by ourselves which is very demanding.

If we would be **able to setup c**losing every 3-6 days? That would be awesome.

Martin

**Comment by recursivetree** [comment]
No, I don't plan on adding it. The idea behind closing it is to confirm that the order is delivered and everything is fine. Otherwise someone could mark his deliveries as completed while not delivering anything, the order get's deleted and there is no trace left.

That being said, you can grant the allianceindustry.admin permission to allow people to close other's orders.

If you have a better solution as for how to make it scam-proof and easier to use, feel free to share it.

**Comment by martinskalicky** [comment]
**I do completely understand the idea of blocking scammers.**

Why i brought this up is that in normal environment we do have pages and pages of contracts which are already done and we have hard time navigating thrue that. U can have only 10 orders per page.

Alternative solution might be adding one menu item into AllianceIndustryPlanner where we do have "Deliveries" now. So adding another menu item where you will find only items which u did not delivered yet. That would solve it. I would propose filter but they cant be saved as i mentioned in #6 

I can imagine "Deliveries" sub-items completed, in progress

Let me know what u think about menu item.

**Comment by recursivetree** [comment]
Isn't it enough to sort your deliveries by wether they are completed?

**Comment by martinskalicky** [comment]
Filters can be saved by now, which is solving this issue. Thank you
