### ISSUE TITLE
Feature: automatically update prices

### ISSUE THREAD

**Issue by martinskalicky** [recursivetree/seat-alliance-industry#5]
Hello,

it would be great if we can setup a tickbox which will enable automatic updates of JITA prices (per 24h?)

Explanation:
- Sometimes orders are waiting in que and when we start to work on them prices are totally different. 

Very nice would be to be able to set in config what would be the duration of automatic updates (per day? week?)

Martin

**Comment by recursivetree** [comment]
That's a good idea. Right now, I'm kind of busy, but it will get better in around a week, so I can implement it. There are still a few things to think about though. If you submit a delivery, the prices for that delivery should remain locked, so you don't have to sell at a price you didn't agree upon initially, right? And there must be some safeguards for the guy creating orders, so he isn't required to buy items at exorbitant prices, just because they price spiked.

**Comment by recursivetree** [comment]
The reasons above is also why I didn't add it in the first place. What do you think about an update prices button? This way the order creator can update the order easily when it doesn't get fulfilled.

**Comment by martinskalicky** [comment]
A) When contract is "accepted" price should be fixed.
B) Either tickbox where u accept moving prices based on JITA or update button. Update button might be cool. Under current price we can write (current jita -10% etc). And when u click on update price it will get current jita price + settings u did before. This might work very well and I think its a way.

**Comment by recursivetree** [comment]
I added a update prices button to the order details page

**Comment by recursivetree** [comment]
it will come out with the next release
